const presetLabels: Record<string, string> = {
  red: "🔴 Красный",
  blue: "🔵 Синий",
  green: "🟢 Зелёный",
  purple: "🟣 Фиолетовый",
  black: "⚫ Чёрный",
  gold: "🟡 Золотой",
  crypto: "₿ Крипто",
  cyberpunk: "🌆 Киберпанк",
  meme: "😄 Мемный",
  gamer: "🎮 Геймер",
  magic: "✨ Магический",
  samurai: "🗡️ Самурай",
  software_engineer: "👨‍💻 Разработчик",
  data_scientist: "📊 Дата-сайентист",
  ai_researcher: "🤖 ИИ-исследователь",
  product_manager: "🧭 Продакт-менеджер",
  ux_designer: "🖌️ UX-дизайнер",
  illustrator: "🎨 Иллюстратор",
  photographer: "📷 Фотограф",
  videographer: "🎥 Видеограф",
  musician: "🎵 Музыкант",
  dj: "🎧 Диджей",
  singer: "🎤 Певец",
  podcaster: "🎙️ Подкастер",
  streamer: "📡 Стример",
  writer: "✍️ Писатель",
  poet: "🪶 Поэт",
  journalist: "📰 Журналист",
  teacher: "📚 Учитель",
  student: "🎓 Студент",
  scientist: "🔬 Учёный",
  doctor: "🩺 Врач",
  nurse: "🏥 Медсестра",
  chef: "👨‍🍳 Шеф-повар",
  baker: "🥐 Пекарь",
  barista: "☕ Бариста",
  bartender: "🍸 Бармен",
  athlete: "🏅 Атлет",
  runner: "🏃 Бегун",
  cyclist: "🚴 Велосипедист",
  skater: "🛹 Скейтер",
  surfer: "🏄 Сёрфер",
  snowboarder: "🏂 Сноубордист",
  climber: "🧗 Скалолаз",
  yogi: "🧘 Йог",
  dancer: "💃 Танцор",
  actor: "🎭 Актёр",
  director: "🎬 Режиссёр",
  architect: "📐 Архитектор",
  engineer: "⚙️ Инженер",
  entrepreneur: "🚀 Предприниматель",
  investor: "📈 Инвестор",
  marketer: "📣 Маркетолог",
  sales_pro: "🤝 Специалист по продажам",
  lawyer: "⚖️ Юрист",
  psychologist: "🧠 Психолог",
  coach: "🗣️ Коуч",
  mechanic: "🔧 Механик",
  pilot: "✈️ Пилот",
  astronaut: "🧑‍🚀 Астронавт",
  firefighter: "🚒 Пожарный",
  detective: "🔎 Детектив",
  gardener: "🌱 Садовод",
  traveler: "🧳 Путешественник",
  explorer: "🧭 Исследователь",
  collector: "🧸 Коллекционер",
  bookworm: "📖 Книголюб",
  cinephile: "🎞️ Киноман",
  anime_fan: "🌸 Аниме-фан",
  comic_fan: "💬 Фан комиксов",
  board_gamer: "🎲 Настольщик",
  chess_player: "♟️ Шахматист",
  tabletop_rpg: "🗺️ Фан настольных ролевых игр",
  football_fan: "⚽ Футбольный фанат",
  basketball_fan: "🏀 Баскетбольный фанат",
  tennis_player: "🎾 Теннисист",
  martial_artist: "🥋 Мастер единоборств",
  boxer: "🥊 Боксёр",
  angler: "🎣 Рыболов",
  pet_lover: "🐾 Любитель питомцев",
  eco_life: "🌿 Эко-лайфстайл",
  minimalist: "▫️ Минималист",
  maximalist: "🔶 Максималист",
  retro: "📻 Ретро",
  streetwear: "🧢 Стритвир",
  luxury: "💎 Люкс",
  dark_academia: "🕯️ Тёмная академия",
  cottagecore: "🧺 Коттеджкор",
  sporty: "🏋️ Спортивный",
  fitness: "💪 Фитнес",
  meditation: "🪷 Медитация",
  startup_founder: "🚀 Основатель стартапа",
  robotics: "🦾 Робототехника",
  maker: "🛠️ Мейкер",
  cosplay: "🪡 Косплей",
  sneakerhead: "👟 Сникерхед",
  fashionista: "🕶️ Фэшн-энтузиаст",
  beauty_guru: "💄 Бьюти-гуру",
  tattoo_artist: "🖋️ Тату-мастер",
  graffiti_artist: "🧱 Граффити-художник",
  woodworker: "🪵 Столяр",
  ceramist: "🏺 Керамист",
  knitter: "🧶 Вязальщик",
  plant_parent: "🪴 Домашний ботаник",
  car_enthusiast: "🏎️ Автоэнтузиаст",
  motorcyclist: "🏍️ Мотоциклист",
  aviation_geek: "🛩️ Фан авиации",
  history_buff: "🏛️ Любитель истории",
  language_learner: "🗣️ Изучает языки",
  foodie: "🍽️ Фуди",
  tea_lover: "🍵 Любитель чая",
  coffee_lover: "☕ Любитель кофе",
  home_cook: "🥘 Домашний кулинар",
  mountain_hiker: "⛰️ Горный хайкер",
  beach_chill: "🏖️ Пляжный чилл",
  festival_goer: "🎪 Фестивальный вайб",
  raver: "🔊 Рейвер",
  lofi: "🎧 Лоу-фай",
  jazz: "🎷 Джаз",
  rockstar: "🎸 Рокстар",
  metalhead: "🤘 Металлист",
  classical_music: "🎻 Классическая музыка",
  hip_hop: "🎤 Хип-хоп",
  k_pop: "🎶 Кей-поп",
  latin_dance: "💃 Латино-танцы",
  travel_blogger: "🌍 Тревел-блогер",
  laptop: "💻 Ноутбук",
  coffee: "☕ Кофе",
  gamepad: "🎮 Геймпад",
  bitcoin_coin: "🪙 Биткоин-монета",
  microphone: "🎙️ Микрофон",
  drumsticks: "🥁 Барабанные палочки",
  tablet: "📱 Планшет",
  smartphone: "📱 Смартфон",
  headphones: "🎧 Наушники",
  camera: "📷 Камера",
  video_camera: "🎥 Видеокамера",
  ring_light: "💡 Кольцевая лампа",
  sketchbook: "📓 Скетчбук",
  paintbrush: "🖌️ Кисть",
  color_palette: "🎨 Палитра",
  guitar: "🎸 Гитара",
  keyboard_synth: "🎹 Синтезатор",
  vinyl_record: "💿 Виниловая пластинка",
  book_stack: "📚 Стопка книг",
  notebook: "📒 Блокнот",
  fountain_pen: "🖋️ Перьевая ручка",
  magnifying_glass: "🔎 Лупа",
  telescope: "🔭 Телескоп",
  microscope: "🔬 Микроскоп",
  stethoscope: "🩺 Стетоскоп",
  chef_spoon: "🥄 Поварская ложка",
  whisk: "🥣 Венчик",
  rolling_pin: "🥖 Скалка",
  coffee_cup: "☕ Чашка кофе",
  tea_cup: "🍵 Чашка чая",
  water_bottle: "💧 Бутылка воды",
  dumbbell: "🏋️ Гантель",
  yoga_mat: "🧘 Коврик для йоги",
  basketball: "🏀 Баскетбольный мяч",
  football_ball: "⚽ Футбольный мяч",
  tennis_racket: "🎾 Теннисная ракетка",
  skateboard: "🛹 Скейтборд",
  surfboard: "🏄 Сёрфборд",
  snowboard: "🏂 Сноуборд",
  hiking_backpack: "🎒 Походный рюкзак",
  compass: "🧭 Компас",
  map: "🗺️ Карта",
  suitcase: "🧳 Чемодан",
  passport: "🛂 Паспорт",
  plant_pot: "🪴 Горшок с растением",
  watering_can: "🚿 Лейка",
  toolbox: "🧰 Ящик инструментов",
  wrench: "🔧 Гаечный ключ",
  helmet: "⛑️ Шлем",
  lab_flask: "🧪 Колба",
  robotic_arm: "🦾 Роборука",
  drone: "🛸 Дрон",
  vr_headset: "🥽 Шлем виртуальной реальности",
  chess_piece: "♟️ Шахматная фигура",
  dice_set: "🎲 Набор кубиков",
  playing_cards: "🃏 Игральные карты",
  comic_book: "💬 Комикс",
  action_camera: "📹 Экшн-камера",
  tripod: "📐 Штатив",
  briefcase: "💼 Портфель",
  calculator: "🧮 Калькулятор",
  chart_board: "📊 Доска с графиком",
  rocket_model: "🚀 Модель ракеты",
  spray_can: "🎨 Баллончик краски",
  thread_spool: "🧵 Катушка ниток",
  sewing_machine: "🪡 Швейная машинка",
  clay_tool: "🏺 Инструмент для глины",
  wood_plane: "🪵 Рубанок",
  recording_mic: "🎙️ Студийный микрофон",
  mixer_controller: "🎛️ Диджей-контроллер",
  turntable: "💿 Проигрыватель",
  neon_sign: "🌟 Неоновая вывеска",
  lantern: "🏮 Фонарь",
  camp_mug: "☕ Походная кружка",
  binoculars: "🔭 Бинокль",
  medal: "🏅 Медаль",
  trophy: "🏆 Кубок",
  ticket_stub: "🎟️ Билет",
  film_clapper: "🎬 Кинохлопушка",
  makeup_brush: "💄 Кисть для макияжа",
  hairdryer: "💨 Фен",
  sneaker: "👟 Кроссовок",
  wristwatch: "⌚ Наручные часы",
  sunglasses: "🕶️ Солнцезащитные очки",
  beanie: "🧢 Шапка бини",
  cap: "🧢 Кепка",
  scarf: "🧣 Шарф",
  hoodie: "👕 Худи",
  backpack: "🎒 Рюкзак",
  bike_helmet: "🚴 Велошлем",
  car_key: "🔑 Ключ от авто",
  motorcycle_helmet: "🏍️ Мотошлем",
  train_ticket: "🎫 Билет на поезд",
  globe: "🌍 Глобус",
  language_flashcards: "🔤 Карточки для языков",
  puzzle_cube: "🧩 Кубик-головоломка",
  arcade_stick: "🕹️ Аркадный стик",
  portable_console: "🎮 Портативная консоль",
  tablet_pen: "✏️ Стилус",
  whiteboard_marker: "🖊️ Маркер",
  smart_speaker: "🔊 Умная колонка",
  fitness_tracker: "⌚ Фитнес-браслет",
  drawing_tablet: "🖍️ Графический планшет",
  ukulele: "🎸 Укулеле",
  saxophone: "🎷 Саксофон",
  meditation_cushion: "🪷 Подушка для медитации",
  gardening_gloves: "🧤 Садовые перчатки",
  neon_server_room: "🌌 Неоновая серверная",
  crypto_chart: "📈 Крипто-график",
  space: "🚀 Космос",
  gaming_room: "🕹️ Геймерская комната",
  castle: "🏰 Замок",
  white_studio: "🤍 Белая студия",
  home_studio: "🏠 Домашняя студия",
  podcast_booth: "🎙️ Подкаст-будка",
  music_studio: "🎚️ Музыкальная студия",
  concert_stage: "🎤 Концертная сцена",
  jazz_club: "🎷 Джаз-клуб",
  rock_stage: "🎸 Рок-сцена",
  art_gallery: "🖼️ Арт-галерея",
  design_studio: "🖌️ Дизайн-студия",
  photo_studio: "📸 Фотостудия",
  film_set: "🎬 Съёмочная площадка",
  cinema_hall: "🎞️ Кинозал",
  library: "📚 Библиотека",
  bookstore: "📖 Книжный магазин",
  classroom: "🏫 Классная комната",
  university_lab: "🎓 Университетская лаборатория",
  science_lab: "🔬 Научная лаборатория",
  clinic_office: "🏥 Кабинет клиники",
  kitchen_studio: "🍳 Кулинарная студия",
  bakery: "🥐 Пекарня",
  coffee_shop: "☕ Кофейня",
  restaurant_kitchen: "🍽️ Ресторанная кухня",
  gym: "🏋️ Тренажёрный зал",
  boxing_gym: "🥊 Боксёрский зал",
  yoga_studio: "🧘 Йога-студия",
  dance_studio: "💃 Танцевальная студия",
  stadium: "🏟️ Стадион",
  basketball_court: "🏀 Баскетбольная площадка",
  tennis_court: "🎾 Теннисный корт",
  skate_park: "🛹 Скейт-парк",
  surf_beach: "🏄 Пляж для сёрфинга",
  mountain_trail: "⛰️ Горная тропа",
  snowy_peak: "🏔️ Снежная вершина",
  forest_camp: "🏕️ Лесной лагерь",
  desert_road: "🏜️ Пустынная дорога",
  tropical_island: "🏝️ Тропический остров",
  city_rooftop: "🌃 Городская крыша",
  loft_apartment: "🏙️ Лофт-квартира",
  streetwear_shop: "🧢 Стритвир-магазин",
  sneaker_wall: "👟 Стена кроссовок",
  fashion_runway: "💃 Модный подиум",
  beauty_studio: "💄 Бьюти-студия",
  tattoo_studio: "🖋️ Тату-студия",
  barbershop: "💈 Барбершоп",
  workshop: "🛠️ Мастерская",
  garage: "🔧 Гараж",
  maker_lab: "🧰 Мейкерская лаборатория",
  robotics_lab: "🦾 Лаборатория робототехники",
  startup_office: "🏢 Стартап-офис",
  trading_desk: "📈 Трейдинг-деск",
  creative_office: "💡 Креативный офис",
  law_library: "⚖️ Юридическая библиотека",
  newsroom: "📰 Ньюсрум",
  writer_room: "✍️ Комната писателя",
  cozy_desk: "🖥️ Уютный рабочий стол",
  greenhouse: "🌿 Оранжерея",
  botanical_garden: "🌺 Ботанический сад",
  comic_store: "💬 Магазин комиксов",
  anime_room: "🌸 Аниме-комната",
  board_game_cafe: "🎲 Кафе настольных игр",
  rpg_tavern: "🗺️ Таверна настольных ролевых игр",
  chess_club: "♟️ Шахматный клуб",
  retro_arcade: "🕹️ Ретро-аркада",
  vr_arena: "🥽 Арена виртуальной реальности",
  esports_stage: "🎮 Киберспортивная сцена",
  space_station: "🛰️ Космическая станция",
  moon_base: "🌕 Лунная база",
  cyber_city: "🌆 Кибер-город",
  samurai_dojo: "⛩️ Самурайское додзё",
  magic_forest: "✨ Магический лес",
  medieval_tavern: "🏰 Средневековая таверна",
  steampunk_lab: "⚙️ Стимпанк-лаборатория",
  vaporwave_mall: "🛍️ Вейпорвейв-молл",
  lofi_room: "🎧 Лоу-фай комната",
  kpop_stage: "🎶 Кей-поп сцена",
  hiphop_block_party: "🎤 Хип-хоп квартал",
  latin_dance_floor: "💃 Латино-танцпол",
  classical_concert_hall: "🎻 Зал классической музыки",
  museum_hall: "🏛️ Музейный зал",
  history_archive: "📜 Исторический архив",
  language_school: "🗣️ Языковая школа",
  travel_airport: "✈️ Аэропорт путешествий",
  train_station: "🚉 Вокзал",
  car_showroom: "🏎️ Автосалон",
  motorcycle_garage: "🏍️ Мотогараж",
  aviation_hangar: "🛩️ Авиационный ангар",
  garden_patio: "🌱 Садовое патио",
  ceramic_studio: "🏺 Керамическая студия",
  sewing_atelier: "🧵 Швейное ателье",
  woodshop: "🪵 Столярная мастерская",
  urban_garden: "🌇 Городской сад",
  night_market: "🌙 Ночной рынок",
  food_truck_street: "🚚 Улица фудтраков",
  tea_house: "🍵 Чайный дом",
  meditation_room: "🪷 Комната медитации",
  minimalist_room: "▫️ Минималистичная комната",
  luxury_lounge: "💎 Люксовый лаунж",
  dark_academia_study: "🕯️ Кабинет тёмной академии",
  cottagecore_kitchen: "🧺 Кухня коттеджкор",
  rainy_city_window: "🌧️ Окно в дождливый город",
  rooftop_party: "🎉 Вечеринка на крыше",
  Epic: "△ Epic",
  Mythic: "◆ Mythic",
  Legendary: "⬢ Legendary",
  "Founder Legendary": "✹ Founder Legendary",
  Foil: "✨ Foil",
  "Foil Epic": "△ Foil Epic",
  "Foil Mythic": "◆ Foil Mythic",
  "Foil Legendary": "⬢ Foil Legendary",
  "Foil Founder Legendary": "✹ Foil Founder Legendary",
  telegram_profile: "📷 Фото Telegram",
  uploaded: "🖼️ Загруженное фото",
  none: "Без фото",
  draft: "Черновик",
  ready_for_generation: "Готова к генерации",
  generating: "Генерируется",
  completed: "Готова",
  failed: "Ошибка генерации",
};

export function getPresetLabel(value: string | null | undefined): string {
  if (!value) {
    return "Пусто";
  }

  return presetLabels[value] ?? value;
}
